// This file is auto-generated from markdown files in content/blog/
// Do not edit this file directly - edit the markdown files instead

export interface BlogPost {
  id: string;
  slug: string;
  title: string;
  excerpt: string;
  content: string;
  category: string; // ID of the category
  tags: string[];
  date: string;
  readTime: string;
  // The 'image' field from frontmatter, if present, is used for the category image.
  // It's not directly part of BlogPost to avoid redundancy, but influences BlogCategory.
}

export interface BlogCategory {
  id: string; // e.g., 'general', 'tech-deep-dive'
  name: string; // e.g., 'General', 'Tech Deep Dive'
  description: string;
  image: string; // URL to an image (from post frontmatter or default)
  postCount: number;
}

export const blogPosts: BlogPost[] = [
  {
    "id": "1",
    "slug": "welcome-to-my-blog",
    "title": "Welcome to My Research Blog",
    "excerpt": "Welcome to my research blog where I share insights, discoveries, and thoughts on computational science and interdisciplinary research.",
    "content": "<h1>Welcome to My Research Blog</h1>\n<p>This is my first blog post! I&#39;m excited to share my research journey with you.</p>\n<h2>What You&#39;ll Find Here</h2>\n<ul>\n<li>Research insights and discoveries</li>\n<li>Computational science tutorials</li>\n<li>Thoughts on interdisciplinary collaboration</li>\n<li>Updates from my academic journey</li>\n</ul>\n<h2>Getting Started</h2>\n<p>To add new blog posts, simply create markdown files in the <code>content/blog/</code> directory. Each post should have frontmatter with title, category, tags, and excerpt.</p>\n<h2>Images in Posts</h2>\n<p>You can add images to your posts like this:</p>\n<p><img src=\"https://images.pexels.com/photos/8386440/pexels-photo-8386440.jpeg?auto=compress&cs=tinysrgb&w=800\" alt=\"Research Setup\"></p>\n<p>Or reference local images from your <code>public/images/blog/</code> folder:</p>\n<pre><code class=\"language-markdown\">![My Research](../public/images/blog/my-research.jpg)\n</code></pre>\n<p>Happy reading!</p>\n",
    "category": "general",
    "tags": [
      "welcome",
      "research",
      "introduction"
    ],
    "date": "2025-06-12",
    "readTime": "1 min read"
  }
];

export const blogCategories: BlogCategory[] = [
  {
    "id": "general",
    "name": "General",
    "description": "Posts about general",
    "image": "https://images.pexels.com/photos/669610/pexels-photo-669610.jpeg?auto=compress&cs=tinysrgb&w=600",
    "postCount": 1
  }
];
