// This file is auto-generated from markdown files in content/journey/
// Do not edit this file directly - edit the markdown files instead

export interface JourneyPost {
  id: string;
  date: string;
  type: 'text' | 'image-text';
  title: string;
  content: string;
  image?: string;
}

export const journeyPosts: JourneyPost[] = [
  {
    "id": "1",
    "date": "2024-09-05",
    "type": "text",
    "title": "Started My Research Website",
    "content": "Excited to launch my new research website! This platform will help me share my work, connect with fellow researchers, and document my academic journey.\r\n\r\nLooking forward to sharing my thought, insights from my readings and research in neurosciences (and, more broadly, biological sciences), and recommendations of books/shows/movies as I encounter more of it."
  }
];
