// This file is auto-generated from markdown files in content/journey/
// Do not edit this file directly - edit the markdown files instead

export interface JourneyPost {
  id: string;
  date: string;
  type: 'text' | 'image-text';
  title: string;
  content: string;
  image?: string;
}

export const journeyPosts: JourneyPost[] = [
  {
    "id": "1",
    "date": "2025-06-12",
    "type": "text",
    "title": "Started My Research Website",
    "content": "Excited to launch my new research website! This platform will help me share my work, connect with fellow researchers, and document my academic journey.\n\nLooking forward to sharing insights from my research in computational science and machine learning."
  }
];
